version: '3.9'
services:
    spark-master:
        build:
          context: spark_base
          dockerfile: dockerfile
        container_name: test-spark-master
        user: root
        restart: on-failure
        volumes:
          - ./app:/app
        environment:
          - SPARK_MODE=master
          - SPARK_MASTER_PORT=7077
          - SPARK_MASTER_WEBUI_PORT=8080
          - SPARK_MASTER_HOST=spark-master
          - SPARK_RPC_AUTHENTICATION_ENABLED=no
          - SPARK_RPC_ENCRYPTION_ENABLED=no
          - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
          - SPARK_SSL_ENABLED=no
          - SPARK_MASTER_URL=spark://spark-master:7077
        ports:
          - 8080:8080
          - 7077:7077
          - 4040:4040
    spark-worker:
        build:
          context: spark_base
          dockerfile: dockerfile
        container_name: test-spark-worker
        user: root
        depends_on:
          - spark-master
        restart: on-failure
        volumes:
          - ./app:/app
        environment:
          - SPARK_MODE=worker
          - SPARK_MASTER_PORT=7077
          - SPARK_MASTER_WEBUI_PORT=8080
          - SPARK_MASTER_HOST=spark-master
          - SPARK_RPC_AUTHENTICATION_ENABLED=no
          - SPARK_RPC_ENCRYPTION_ENABLED=no
          - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
          - SPARK_SSL_ENABLED=no
          - SPARK_MASTER_URL=spark://spark-master:7077
        ports:
          - 8081:8081
    spark-tester-1:
      build:
        context: app
        dockerfile: dockerfile
      user: root
      container_name: spark-tester-1
      command: sleep infinity
      volumes:
        - .:/app
      depends_on:
        - spark-master
        - spark-worker
      environment:
        - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        - PYSPARK_SUBMIT_ARGS='pyspark-shell'
        - "SPARK_MASTER=spark://spark-master:7077"
      network_mode: host #Important stuff
    app:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: azurite
      volumes:
        - /:/opt/azurite/folder
      ports:
        - 10000:10000

