FROM python:3.9.7-slim
RUN apt-get update --allow-releaseinfo-change

RUN pip install --upgrade pip

RUN apt-get update && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean;
COPY ../req.txt /
RUN pip install -r req.txt
